flags:
  highlighting-kate: { pcre-light: true }
packages:
  - '.'
  - location: '../indieweb-algorithms'
    extra-dep: true
  - location: '../pcre-heavy'
    extra-dep: true
  - location: '../microformats2-parser'
    extra-dep: true
  - location: '../gitson'
    extra-dep: true
  - location: '../http-link-header'
    extra-dep: true
  - location:
      git: https://github.com/myfreeweb/haskell-socket-activation.git
      commit: c67f50d80e4b83515e88672cbd689d4383710b23
    extra-dep: true
extra-deps:
  - git-embed-0.1.0
  - highlighting-kate-0.6.3
  - wai-cli-0.1.0
resolver: nightly-2016-12-16
