flags:
  highlighting-kate: { pcre-light: true }
packages:
  - '.'
  - location: '../indieweb-algorithms'
    extra-dep: true
  - location: '../../gitson'
    extra-dep: true
extra-deps:
  - highlighting-kate-0.6.4 # for the flags
  - data-has-0.2.1.0
  - hasql-pool-0.4.1
  - wai-cli-0.1.0
resolver: lts-8.2
