version: 0.2

phases:
  build:
    commands:
      - npm config set prefix ~/.local
      - npm i -g npm@5
      - ~/.local/bin/npm i
      #- wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-git-64bit-static.tar.xz
      #- tar -xvf ffmpeg-git-64bit-static.tar.xz
      #- rm ffmpeg-git-64bit-static.tar.xz

artifacts:
  files:
    - "**/*"
